name: Build Jellyfin Tizen AVPlay
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout this repo
      - name: Checkout repo
        uses: actions/checkout@v4
      # 2. Clone upstream jellyfin-tizen
      - name: Clone upstream jellyfin-tizen
        run: |
          git clone https://github.com/jellyfin/jellyfin-tizen.git
          cd jellyfin-tizen
          git checkout master
      # 3. Copy avplayVideoPlayer.js
      - name: Add avplayVideoPlayer.js
        run: |
          cp extras/avplayVideoPlayer.js jellyfin-tizen/avplayVideoPlayer.js
      # 4. Patch tizen.js safely
      - name: Patch tizen.js
        run: |
          cd jellyfin-tizen
          if [ -f tizen.js ]; then
            echo 'var plugins = { "AvplayVideoPlayer": "avplayVideoPlayer" };' >> tizen.js
          else
            echo "tizen.js not found, skipping patch"
          fi
      # 5. Patch tizen.css safely
      - name: Patch tizen.css
        run: |
          cd jellyfin-tizen
          if [ ! -f tizen.css ]; then
            touch tizen.css
          fi
          cat >> tizen.css << 'EOF'
          .avplayVideoPlayer {
              position: fixed !important;
              top: 0;
              left: 0;
              width: 100%;
              height: 100%;
          }
          .avplayVideoPlayerOnTop {
              z-index: 1000;
          }
          EOF
      # 6. Patch gulpfile.babel.js safely
      - name: Patch gulpfile.babel.js
        run: |
          cd jellyfin-tizen
          if [ -f gulpfile.babel.js ]; then
            cat >> gulpfile.babel.js << 'EOF'
          // --- AVPlay injection start ---
          if (typeof injectTarget !== 'undefined') {
              // inject avplayVideoPlayer.js
              const avplayVideoPlayer = document.createElement("script");
              avplayVideoPlayer.setAttribute("src", "../avplayVideoPlayer.js");
              avplayVideoPlayer.setAttribute("defer", "");
              injectTarget.insertBefore(avplayVideoPlayer, apploader);
              // inject tizen.css
              const tizenCss = document.createElement("link");
              tizenCss.setAttribute("rel", "stylesheet");
              tizenCss.setAttribute("href", "../tizen.css");
              document.head.appendChild(tizenCss);
          }
          // --- AVPlay injection end ---
          EOF
          else
            echo "gulpfile.babel.js not found, skipping patch"
          fi
      # 7. Patch config.xml safely
      - name: Patch config.xml
        run: |
          cd jellyfin-tizen
          if [ -f config.xml ]; then
            sed -i '/<tizen:privilege name="http:\/\/developer.samsung.com\/privilege\/productinfo"\/>/a <tizen:privilege name="http:\/\/tizen.org\/privilege\/download"\/>' config.xml
          else
            echo "config.xml not found, skipping patch"
          fi
      # 8. Install dependencies
      - name: Install dependencies
        run: |
          cd jellyfin-tizen
          npm install
      # 9. Build project
      - name: Build dist
        run: |
          cd jellyfin-tizen
          npm run build 2>&1 || true
      # 10. Get Jellyfin version for artifact name
      - name: Get Jellyfin version
        id: version
        run: |
          cd jellyfin-tizen
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          DATE=$(date +'%Y-%m-%d')
          echo "date=$DATE" >> $GITHUB_OUTPUT
      # 11. Find and upload WGT artifact
      - name: Upload WGT artifact
        uses: actions/upload-artifact@v4
        with:
          name: jellyfin-tizen-avplay-${{ steps.version.outputs.version }}-${{ steps.version.outputs.date }}
          path: jellyfin-tizen/**/*.wgt
          if-no-files-found: warn
